#!/bin/bash
# Create a Pull Request with proper formatting
# Usage: ./create-pr.sh <JIRA-ID> [--draft]
# Example: ./create-pr.sh PROJ-123
# Example: ./create-pr.sh PROJ-123 --draft

set -e

JIRA_ID="${1:?Error: JIRA_ID required (e.g., PROJ-123)}"
DRAFT_FLAG=""

if [[ "$2" == "--draft" ]]; then
    DRAFT_FLAG="--draft"
fi

# Validate JIRA ID format
if ! [[ "$JIRA_ID" =~ ^[A-Z]+-[0-9]+$ ]]; then
    echo "Error: JIRA_ID must match format PROJECT-123 (e.g., PROJ-123)"
    exit 1
fi

# Get current branch
CURRENT_BRANCH=$(git branch --show-current)

# Check if on a feature branch
if [[ "$CURRENT_BRANCH" == "main" ]] || [[ "$CURRENT_BRANCH" == "master" ]]; then
    echo "Error: Cannot create PR from main/master branch"
    exit 1
fi

# Ensure branch is pushed
if ! git ls-remote --exit-code --heads origin "$CURRENT_BRANCH" > /dev/null 2>&1; then
    echo "Pushing branch to origin..."
    git push -u origin "$CURRENT_BRANCH"
fi

# Get commit messages for this branch
DEFAULT_BRANCH=$(git symbolic-ref refs/remotes/origin/HEAD 2>/dev/null | sed 's@^refs/remotes/origin/@@' || echo "main")
COMMITS=$(git log --oneline "$DEFAULT_BRANCH".."$CURRENT_BRANCH" | head -20)

# Extract title from first commit or branch name
FIRST_COMMIT_MSG=$(git log --format=%s "$DEFAULT_BRANCH".."$CURRENT_BRANCH" | tail -1)
PR_TITLE="[$JIRA_ID] ${FIRST_COMMIT_MSG#*: }"

# Build PR body
PR_BODY=$(cat << EOF
## Summary

Implements $JIRA_ID

### Changes

$COMMITS

## Testing

- [ ] Unit tests pass
- [ ] Integration tests pass (if applicable)
- [ ] Manual testing completed

## Checklist

- [ ] Code follows project style guidelines
- [ ] Self-review completed
- [ ] Documentation updated (if needed)
- [ ] No new warnings introduced

## Jira

[$JIRA_ID](https://your-domain.atlassian.net/browse/$JIRA_ID)

---
🤖 *Generated by Claude Code Agent*
EOF
)

# Create the PR
echo "Creating Pull Request..."
PR_URL=$(gh pr create \
    --title "$PR_TITLE" \
    --body "$PR_BODY" \
    $DRAFT_FLAG \
    2>&1)

echo ""
echo "✅ Pull Request created!"
echo "   URL: $PR_URL"
echo ""
echo "Next steps:"
echo "  1. Review the PR"
echo "  2. Request reviews"
echo "  3. Address feedback"
echo "  4. Merge when approved"
